before_install:
  - which bundle || gem install bundler
  # - sudo apt-get -qq update
  # - sudo apt-get install -y libxml2-dev

env: CC_TEST_REPORTER_ID=5d31b2346aeac0c9193eb75b3e85657dcb1b84bf9902bf688b9ccec846d32489
language: ruby
language: ruby
rvm:
 #- 2.2
 - 2.4.0
 # - jruby
 # - rbx-2
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec spec
  - bundle exec cucumber

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  # - rake db:migrate RAILS_ENV=test
  - rake db:setup
